### ISSUE TITLE
PHP 8 breaking change, and thank you for this wonderful tool

### ISSUE THREAD

**Issue by ColonelBuendia** [KrISS/bang#1]
First, I adore this project and have been using it everyday for at least a year or two.  Thanks so much for it.  

I moved to PHP 8.0+ as  PHP 7.4 isn't in the default repos for my distro anymore, and this was not running.  The temporary solution I got to is listed below, though I am not sure if it's optimal (or even well advised for that matter).  

On lines 1924 and 1925 of the compiled file

```php
$slugs = join(array_merge(array_filter(array_keys($this->singleClasses), 'is_string'),array_filter(array_keys($this->listClasses), 'is_string')), '|');
$slugsId = join(array_filter(array_keys($this->listClasses), 'is_string'), '|');
```

to 

```php
$slugs = join('|', array_merge(array_filter(array_keys($this->singleClasses), 'is_string'),array_filter(array_keys($this->listClasses), 'is_string')));
$slugsId = join('|', array_filter(array_keys($this->listClasses), 'is_string'));
```

Thanks again.

**Comment by tontof** [comment]
Thanks for your message!

My bad, I've forgot to update the KrISS bang code from KrISS mvvm. Your modification is correct:
https://github.com/KrISS/mvvm/commit/eeaa949868e3cf3670096969f15458f594f0c89a
I've updated KrISS bang.
https://github.com/KrISS/bang/commit/8e81d4b169c9170b1eecb54b19626c0a5f37fa86

Thanks for the notification!

**Comment by ColonelBuendia** [comment]
Great, thanks again.
